### ISSUE TITLE
can you guys add steins;gate VNs 

### ISSUE THREAD

**Issue by coding-garden-1** [Open-Wine-Components/umu-database#35]
not an issue but can yall add that :)

**Comment by GloriousEggroll** [comment]
If theres no protonfixes needed for the games then theres no reason to add them

**Comment by raven-intheclouds** [comment]
> If theres no protonfixes needed for the games then theres no reason to add them

Please consider adding games that work out of the box to the db/filesystem. This way, the community will know if it works or not already, not duplicating efforts.

**Comment by strycore** [comment]
Unless we plan to add every video game released for Windows, I don't think this is a good way to keep track of which games don't need any fixes. And if we did import every Windows game ever made, a bunch of them would require fixes so it still wouldn't be a good way to track games. 

Better use a rating system like ProtonDB or Steam Deck Verified. Lutris will have one too eventually.

**Comment by GloriousEggroll** [comment]
closing as original question was answered.
