### ISSUE TITLE
Clarification about adding new entries to the database

### ISSUE THREAD

**Issue by Nocifer** [Open-Wine-Components/umu-database#39]
After having already submitted 3 PRs for 4 new games not on the database, I stumbled upon this reply in #35:

> If theres no protonfixes needed for the games then theres no reason to add them

So it's only when a protonfix is required for a game that it needs to be added to the database? Can we still add other games for completeness' sake, or is that discouraged? If so, then only 1 of my 3 PRs (Planescape: Torment requires `openal`) is actually valid. Perhaps this should be better clarified somewhere in the README?

Further, how exactly do I identify a game that actually needs a protonfix besides trying and failing to launch it? Regarding PS:T, as far as I can tell there is no protonfix entry/file for either `466300` (Steam ID) or `1203613131` (GOG ID) even though it requires `openal`. Am I doing something wrong here (perhaps I'm misinterpreting what counts as a protonfix) or is this a corner case of a game actually missing entirely from the protonfixes list?

**Comment by Root-Core** [comment]
Sorry if this is a silly question, but do we even need the database in the first place?
We could use the folder structure for the mapping instead.

Example:
```
gamefixes-egs/a0b8d4482f3d4f939f35f87a3f367865.py -> ../gamefixes-steam/19900.py
gamefixes-egs/25ad72f164b948ab9e05eb18fab2cda8.py
```

Or even:
```
gamefixes-egs/a0b8d4482f3d4f939f35f87a3f367865.py -> "../gamefixes/Far Cry 2.py"
gamefixes-steam/19900.py -> "../gamefixes/Far Cry 2.py"
gamefixes-egs/25ad72f164b948ab9e05eb18fab2cda8.py -> "../gamefixes/CYGNI: All Guns Blazing.py"
```

Not only would this eliminate any telemetry / privacy concerns, it doesn't even require internet access.
On top of that, we'd only have entries for the fixes that were actually used.

**Comment by strycore** [comment]
For the Lutris implementation, there are no online requirements or privacy concerns. The umu database it processed on the website and delivered as a runtime component. Once it's downloaded, everything is done locally.

The code on the Lutris website scans the Protonfixes repo to filter out games that don't require a fix so it doesn't matter if some games are in the database and don't require any fix, they won't be present in the final umu-games.json file.

**Comment by strycore** [comment]
> Further, how exactly do I identify a game that actually needs a protonfix besides trying and failing to launch it? Regarding PS:T, as far as I can tell there is no protonfix entry/file for either 466300 (Steam ID) or 1203613131 (GOG ID) even though it requires openal. Am I doing something wrong here (perhaps I'm misinterpreting what counts as a protonfix) or is this a corner case of a game actually missing entirely from the protonfixes list?

The protonfixes repo doesn't cover every game available on Steam or GOG so it's perfectly possible that some are missing. In that case, it's recommended to also submit the fix in a PR. 
Usually, anything that requires winetricks, registry edits or other fixes in order to run should be a protonfix. A good starting point could be the existing Lutris scripts or comment in ProtonDB to confirm the fix is needed. For Lutris, double check the fix is actually needed in the latest version since some of them can be pretty old.

**Comment by Root-Core** [comment]
> For the Lutris implementation, there are no online requirements or privacy concerns. The umu database it processed on the website and delivered as a runtime component. Once it's downloaded, everything is done locally.

There's a request in `umu-protonfixes`, which at least spawns some metadata.
It'll be called once for non-steam games, if I'm not mistaken.

https://github.com/Open-Wine-Components/umu-protonfixes/blob/80327b8c98ceec24bec288d0df44d7828310f0e7/fix.py#L65

I'm not too worried about this, but I'm just not sure if this database is really necessary. I'm only looking at `umu-protonfixes`, and I don't know if it's used anywhere else. In my opinion, it's not that useful there.

**Comment by Root-Core** [comment]
Getting the `umu_id` from that site was recently added to Heroic via https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/3724

https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/blob/a579cb4f659593103936adb9985e01f7c81003f4/src/backend/wiki_game_info/umu/utils.ts

**Comment by Nocifer** [comment]
> > Further, how exactly do I identify a game that actually needs a protonfix besides trying and failing to launch it? Regarding PS:T, as far as I can tell there is no protonfix entry/file for either 466300 (Steam ID) or 1203613131 (GOG ID) even though it requires openal. Am I doing something wrong here (perhaps I'm misinterpreting what counts as a protonfix) or is this a corner case of a game actually missing entirely from the protonfixes list?
> 
> The protonfixes repo doesn't cover every game available on Steam or GOG so it's perfectly possible that some are missing. In that case, it's recommended to also submit the fix in a PR. Usually, anything that requires winetricks, registry edits or other fixes in order to run should be a protonfix. A good starting point could be the existing Lutris scripts or comment in ProtonDB to confirm the fix is needed. For Lutris, double check the fix is actually needed in the latest version since some of them can be pretty old.

I checked the scripts for both the original and the enhanced edition and I don't see any mention of OpenAL in either of them, but I just verified that the game still needs it, both with vanilla Wine (Staging) and with Proton, otherwise it spits out this error:

>0024:err:module:import_dll Library OpenAL32.dll (which is needed by L"Z:\\home\\nocifer\\Games\\Planescape Torment - Enhanced Edition\\Torment.exe") not found
0024:err:module:loader_init Importing dlls for L"Z:\\home\\nocifer\\Games\\Planescape Torment - Enhanced Edition\\Torment.exe" failed, status c0000135

I find it weird that an error so seemingly prominent in a game so famous (and so old) isn't already taken care of in its Lutris script and also doesn't have an accompanying protonfix, so maybe I'm doing something wrong? On the other hand, it does have a perfectly working native Linux version, so maybe nobody bothered to try it with Wine (or they tried, failed, and promptly switched to the Linux version which works OOTB).

I think I'll try submitting a PR for a protonfix.

**Comment by GloriousEggroll** [comment]
Closing this as
1: question regarding whether or not database is required has been covered here:
https://github.com/Open-Wine-Components/umu-protonfixes/issues/137#issuecomment-2414147916

2: code querying umu website for game titles has been rewritten so it checks a locally included database copy instead here:
https://github.com/Open-Wine-Components/umu-protonfixes/commit/eea2879b27c6a0b52cd4f4669e9763d9b86f9f44

3. Troubleshooting game-specific problems is outside the scope of the topic of this issue
